"""SBOZOR ORM modellari.

`Base.metadata` — Alembic `target_metadata` sining yagona manbai. Har bir
model moduli SHU YERDA import qilinishi shart: import qilinmagan modul
metadata'ga tushmaydi va autogenerate uni "o'chirilgan jadval" deb hisoblab
`op.drop_table()` taklif qiladi.
"""

from __future__ import annotations

from sbozor_core.models.base import (
    NAMING_CONVENTION,
    Base,
    TenantMixin,
    TimestampMixin,
    market_fk_column,
    uuid_pk,
)
from sbozor_core.models.identity import (
    LOCALE_CHECK,
    LOCALE_VALUES,
    ROLE_VALUES,
    ROLES_SUBSET_CHECK,
    Market,
    RefreshToken,
    User,
    UserMarketRole,
)
from sbozor_core.models.market import (
    OPEN_WEEKDAYS_CHECK,
    STALL_CODE_SORT_EXPR,
    STALL_STATUS_CHECK,
    STALL_STATUS_VALUES,
    TARIFF_BUSINESS_DATE_EXPR,
    MarketCalendarException,
    MarketProfile,
    Stall,
    StallAssignment,
    StallCategory,
    StallCategoryPeriod,
    StallCodeRegistry,
    Tariff,
    Vendor,
    Zone,
)
from sbozor_core.models.nvr import (
    CAMERA_STATUS_CHECK,
    CAMERA_STATUS_VALUES,
    CAPTURE_STREAM_CHECK,
    CAPTURE_STREAM_VALUES,
    DISCOVERY_RUN_ACTIVE_STATUSES,
    DISCOVERY_RUN_STATUS_CHECK,
    DISCOVERY_RUN_STATUS_VALUES,
    Camera,
    NvrCredential,
    NvrDevice,
    NvrDiscoveryRun,
)
from sbozor_core.models.ops import AUDIT_BUSINESS_DATE_EXPR, AuditLog, SystemHeartbeat
from sbozor_core.models.snapshot import (
    ALERT_OPEN_INDEX,
    ALERT_OPEN_PREDICATE,
    ALERT_SEVERITY_CHECK,
    ALERT_SEVERITY_VALUES,
    CAPTURE_BUSINESS_DATE_EXPR,
    CAPTURE_DUE_INDEX,
    CAPTURE_DUE_PREDICATE,
    CAPTURE_METHOD_CHECK,
    CAPTURE_METHOD_VALUES,
    CAPTURE_OVERDUE_INDEX,
    CAPTURE_OVERDUE_PREDICATE,
    CAPTURE_RUN_ACTIVE_STATUSES,
    CAPTURE_RUN_STATUS_CHECK,
    CAPTURE_RUN_STATUS_VALUES,
    DEFAULT_SNAPSHOT_SLOTS,
    SNAPSHOT_BUSINESS_DATE_EXPR,
    SNAPSHOT_LIGHT_MODE_CHECK,
    SNAPSHOT_LIGHT_MODE_VALUES,
    SNAPSHOT_QUALITY_CHECK,
    SNAPSHOT_QUALITY_VALUES,
    SNAPSHOT_TIER_CHECK,
    SNAPSHOT_TIER_VALUES,
    AlertEvent,
    CaptureRun,
    Snapshot,
    SnapshotSchedule,
    SnapshotScheduleSlot,
)

__all__ = [
    "ALERT_OPEN_INDEX",
    "ALERT_OPEN_PREDICATE",
    "ALERT_SEVERITY_CHECK",
    "ALERT_SEVERITY_VALUES",
    "AUDIT_BUSINESS_DATE_EXPR",
    "CAMERA_STATUS_CHECK",
    "CAMERA_STATUS_VALUES",
    "CAPTURE_BUSINESS_DATE_EXPR",
    "CAPTURE_DUE_INDEX",
    "CAPTURE_DUE_PREDICATE",
    "CAPTURE_METHOD_CHECK",
    "CAPTURE_METHOD_VALUES",
    "CAPTURE_OVERDUE_INDEX",
    "CAPTURE_OVERDUE_PREDICATE",
    "CAPTURE_RUN_ACTIVE_STATUSES",
    "CAPTURE_RUN_STATUS_CHECK",
    "CAPTURE_RUN_STATUS_VALUES",
    "CAPTURE_STREAM_CHECK",
    "CAPTURE_STREAM_VALUES",
    "DEFAULT_SNAPSHOT_SLOTS",
    "DISCOVERY_RUN_ACTIVE_STATUSES",
    "DISCOVERY_RUN_STATUS_CHECK",
    "DISCOVERY_RUN_STATUS_VALUES",
    "LOCALE_CHECK",
    "LOCALE_VALUES",
    "NAMING_CONVENTION",
    "OPEN_WEEKDAYS_CHECK",
    "ROLES_SUBSET_CHECK",
    "ROLE_VALUES",
    "SNAPSHOT_BUSINESS_DATE_EXPR",
    "SNAPSHOT_LIGHT_MODE_CHECK",
    "SNAPSHOT_LIGHT_MODE_VALUES",
    "SNAPSHOT_QUALITY_CHECK",
    "SNAPSHOT_QUALITY_VALUES",
    "SNAPSHOT_TIER_CHECK",
    "SNAPSHOT_TIER_VALUES",
    "STALL_CODE_SORT_EXPR",
    "STALL_STATUS_CHECK",
    "STALL_STATUS_VALUES",
    "TARIFF_BUSINESS_DATE_EXPR",
    "AlertEvent",
    "AuditLog",
    "Base",
    "Camera",
    "CaptureRun",
    "Market",
    "MarketCalendarException",
    "MarketProfile",
    "NvrCredential",
    "NvrDevice",
    "NvrDiscoveryRun",
    "RefreshToken",
    "Snapshot",
    "SnapshotSchedule",
    "SnapshotScheduleSlot",
    "Stall",
    "StallAssignment",
    "StallCategory",
    "StallCategoryPeriod",
    "StallCodeRegistry",
    "SystemHeartbeat",
    "Tariff",
    "TenantMixin",
    "TimestampMixin",
    "User",
    "UserMarketRole",
    "Vendor",
    "Zone",
    "market_fk_column",
    "uuid_pk",
]
